### ISSUE TITLE
Highlighting sometimes isn't applied when doing a Diff

### ISSUE THREAD

**Issue by stephenmcd1** [madskristensen/TextmateBundleInstaller#18] opened 2016-09-20 16:55 UTC
### Installed product versions
- Visual Studio: 2015 Enterprise
- This extension: 1.2.17

### Description
When I run a compare on project files, no syntax highlighting occurs.  However, if I open the same file normally, syntax highlighting does occur.  I've tried doing compares of a few other file types and they have all worked so perhaps there is something special with project files (or I may not have done enough testing to notice a pattern).

### Steps to recreate
1. Make a change to a project file under source control (e.g. add a new file)
2. Run a Compare on the .csporj file and notice no syntax highlighting occurs
3. Unload the project (right click --> Unload Project) and then edit the project file directly.  Notice that syntax highlighting, autocompletion, etc. all functions as expected

### Current behavior
No syntax highlighting when doing a diff
![diffnohighlight](https://cloud.githubusercontent.com/assets/3478394/18680291/f1df1356-7f17-11e6-94c9-1a9a82ea41ab.png)

But is highlighted when editing normally:
![projfilehighlighting](https://cloud.githubusercontent.com/assets/3478394/18680347/249bd6ee-7f18-11e6-8f2f-0d404c8269c7.png)

I also noticed that the extension is aware that it can't do the highlighting because it adds a "Report missing language support for .csproj files" to the context menu when doing a diff (but that is is not added when editing the file normally)

### Expected behavior
Ideally the syntax highlighting would occur when looking at the diff.

**Comment by madskristensen** [comment] 2016-09-20 17:07
This extension doesn't effect the Diff View window in VS at all. The XML editor should handle the syntax highlighting but for some reason it doesn't. It looks like you've got some extension installed that modifies the XML classification and it might be the issue. Try disabling it to see if it helps. If it doesn't, please open a bug on connect.microsoft.com or send feedback through the _Send a Smile/Frown_ feature in VS.

Closing here since the issue isn't caused by this extension

**Closed by madskristensen** 2016-09-20 17:07 UTC

**Comment by stephenmcd1** [comment] 2016-09-20 17:23
Thanks for the quick reply.  I can reproduce without any extensions so I'll follow-up with feedback to VS.
