### ISSUE TITLE
Missing support for .pug files

### ISSUE THREAD

**Issue by JustinRvt** [madskristensen/TextmateBundleInstaller#43] opened 2016-10-21 12:23 UTC
Got VS2015 Community and 1.6.46 version.
Renaming to jade does the trick but messes with the project.

**Comment by madskristensen** [comment] 2016-10-21 16:23
.pug files work for me. See this

![image](https://cloud.githubusercontent.com/assets/1258877/19605568/e4635262-976f-11e6-9033-a6bbbf10ba6e.png)

**Comment by madskristensen** [comment] 2016-10-25 16:07
Dupe of #6

**Closed by madskristensen** 2016-10-25 16:07 UTC
