### ISSUE TITLE
Missing support for .tt files

### ISSUE THREAD

**Issue by ensleep** [madskristensen/TextmateBundleInstaller#259] opened 2017-04-14 01:12 UTC
because we use OracleManagedAccess,so we can not use the entity framework in vs.But we use t4 to gener the models from the oracle db.But now there is no t4 highlight supported in visual studio 2017 and market.We need it.

**Comment by madskristensen** [comment] 2017-04-14 01:47
Dupe of #7

**Closed by madskristensen** 2017-04-14 01:47 UTC
