### ISSUE TITLE
Missing support for .tt files

### ISSUE THREAD

**Issue by svdgriendt** [madskristensen/TextmateBundleInstaller#248] opened 2017-04-01 13:44 UTC
We're editing the standard .tt files provided by Entity Framework. Currently the text is shown as if it's a flat text file. It would be nice to have support for them just like Razor views, which to us seem very similar.

There are "editors" out there, but they don't nearly integrate in Visual Studio (2017) as well as you would expect. Especially when using a different theme than the light one. Also they don't seem to work (yet) with Visual Studio 2017, so it's all about old school editing for now.

**Comment by madskristensen** [comment] 2017-04-02 12:24
Dupe of #7

**Closed by madskristensen** 2017-04-02 12:24 UTC
