### ISSUE TITLE
Missing support for .tt files - T4

### ISSUE THREAD

**Issue by airomero** [madskristensen/TextmateBundleInstaller#242] opened 2017-03-28 02:46 UTC
### Installed product versions
- Visual Studio 2017 Enterprise
- This extension: 2.6.118

### Description
Tangible t4 Editor is not supporting VS 2017, I think is time to include T4 ;)

**Comment by madskristensen** [comment] 2017-03-28 03:31
Dupe of #7

**Closed by madskristensen** 2017-03-28 03:31 UTC
